### ISSUE TITLE
Error on Google Auth

### ISSUE THREAD

**Issue by avinashmane** [jrweb247/oauth-pencilblue#2]
Node v7.5.0
npm 3.8.5

Browser message: 
------------------
Proxy Error 
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /oauth/google/callback.
Reason: Error reading from remote server
Apache/2.2.15 (Red Hat) Server at says-xxxxx.rhcloud.com Port 80

Log:
----
2017-02-15T07:49:32.249Z - error: [1] Router: An unhandled error occurred after calling middleware "render": TypeError: Cannot read property '0' of undefined
    at Object.getEmail (/var/lib/openshift/58a285af89f5cf409700005/app-root/runtime/repo/plugins/oauth-pencilblue/services/oauth_service.js:32:35)
    at Request._callback (/var/lib/openshift/58a285af89f5cf409700005/app-root/runtime/repo/plugins/oauth-pencilblue/services/oauth_service.js:182:45)
    at Request.self.callback (/var/lib/openshift/58a285af89f5cf409700005/app-root/runtime/repo/node_modules/simple-oauth2/node_modules/request/main.js:122:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:192:7)
    at Request.<anonymous> (/var/lib/openshift/58a285af89f5cf409700005/app-root/runtime/repo/node_modules/simple-oauth2/node_modules/request/main.js:661:16)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:189:7)
    at IncomingMessage.<anonymous> (/var/lib/openshift/58a285af89f5cf409700005/app-root/runtime/repo/node_modules/simple-oauth2/node_modules/request/main.js:623:14)
    at emitNone (events.js:91:20)
(node:451667) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property '0' of undefined
(node:451667) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit 
code.

callback url:
------------
http://says-xxxxxx.rhcloud.com/oauth/google/callback?state=3(%230/!~&code=4/gYYjZvwIDcjl8ApEeCXYC4EbxTa7CfpvyaXtGaPCjkU#

**Comment by avinashmane** [comment]
dont have pencil anymore
